// Generate the one52 part -> .usdc mapping manifest for the iOS app. One row per distinct one52
// part id (derived from our glossary, no USM codes), with parsed dims, family, side, a suggested
// asset filename, and an identity meshCorrection placeholder to calibrate once per asset.
// Covers all RESOLVABLE real Haller part types from the imported model (not just one scene),
// annotated with how many appear in the reference scene (out/placement.json) if present.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { identity } from "./export_ios.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const model = JSON.parse(readFileSync(join(ROOT, "out", "model.json"), "utf8"));

// scene counts (optional)
const counts: Record<string, number> = {};
const pf = join(ROOT, "out", "placement.json");
if (existsSync(pf)) for (const p of JSON.parse(readFileSync(pf, "utf8")).parts ?? []) { const id = identity(p.type).part; counts[id] = (counts[id] ?? 0) + 1; }

const ABSTRACT = /^(ct_|dt_|co_|printview|part_)|dummy|prototype/i;
const rows = new Map<string, any>();
for (const c of model.components) {
  const t: string = c.type;
  if (ABSTRACT.test(t)) continue;
  const id = identity(t);
  if (!id.resolved) continue;        // no glossary term -> skip (don't emit a raw German code)
  if (rows.has(id.part)) continue;
  const dm = id.label.match(/(\d+)\s*×\s*(\d+)/), sm = id.label.match(/(\d+)\s*mm/);
  const dims = dm ? [+dm[1], +dm[2]] : sm ? [+sm[1]] : [];
  const side = /\bleft\b/i.test(id.label) ? "left" : /\bright\b/i.test(id.label) ? "right" : null;
  rows.set(id.part, {
    part: id.part, label: id.label, family: id.family, dims, side,
    mesh: id.part + ".usdc",                 // suggested asset filename (fill in / rename as needed)
    meshCorrection: [0, 0, 0, 1],            // calibrate once per asset (see IOS_INTEGRATION.md §5)
    sceneCount: counts[id.part] ?? 0,
  });
}
const parts = [...rows.values()].sort((a, b) => a.family.localeCompare(b.family) || a.part.localeCompare(b.part));

writeFileSync(join(ROOT, "out", "part_manifest.json"), JSON.stringify({
  owner: "one52",
  note: "one52 part -> mesh manifest. Geometry-only mapping derived from the one52 configurator engine; contains no USM proprietary identifiers. Fill `mesh` and calibrate `meshCorrection` (one rotation per .usdc, NOT per instance).",
  parts,
}, null, 1));

const md = [
  "# one52 — part → mesh manifest", "",
  "Auto-generated by `node src/engine/manifest.ts`. one52-owned (no USM codes). The iOS app keys",
  "every placed part by `part` (id); map it to a `.usdc` and calibrate `meshCorrection` once per",
  "asset (see [IOS_INTEGRATION.md](IOS_INTEGRATION.md) §5). `scene` = count in the reference project.", "",
  `Distinct resolvable parts: **${parts.length}**`, "",
  "| part (id) | label | family | dims (mm) | side | mesh | calibrated | scene |",
  "|---|---|---|---|---|---|---|---|",
  ...parts.map((r) => `| \`${r.part}\` | ${r.label} | ${r.family} | ${r.dims.join(" × ") || "—"} | ${r.side ?? "—"} | \`${r.mesh}\` | ☐ | ${r.sceneCount || ""} |`),
].join("\n");
writeFileSync(join(ROOT, "PART_MANIFEST.md"), md + "\n");

console.log(`wrote out/part_manifest.json + PART_MANIFEST.md — ${parts.length} distinct one52 parts`);
const byFam: Record<string, number> = {};
for (const p of parts) byFam[p.family] = (byFam[p.family] ?? 0) + 1;
console.log("  by family: " + Object.entries(byFam).sort((a, b) => b[1] - a[1]).map(([f, n]) => `${f} ${n}`).join(", "));
console.log("  in reference scene: " + parts.filter((p) => p.sceneCount).length + " types");
